# Site settings
title: Jacopo Rabolini | Web Designer
description: "Mi occupo di web disign, grafica, web writing e sviluppo web."
url: "http://www.jacoporabolini.com"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: ""
markdown: kramdown

source: .
destination: ./_site
permalink: /:title/
paginate: 8
paginate_path: /page:num/
exclude: [node_modules, gulpfile.js, package.json]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

# Plugins
gems:
  - jekyll-paginate
